/**
 * Everything the backend reads from its environment, with defaults that match a local test
 * network. Values that have to agree with what was deployed are fixed rather than configurable.
 */
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// Resolves the same from src/ under tsx and from dist/ after a build, since both sit one level
// below the package root.
const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");

export const config = {
  fabricChannelName: process.env.FABRIC_CHANNEL_NAME ?? "milkchannel",
  // Fixed rather than configurable. The deploy script commits the definitions under these names
  // and the supply-chain chaincode names the registry when it calls across to it, so a variable
  // here would only ever change one of the three and break the other two.
  stakeholderChaincodeName: "stakeholder",
  supplychainChaincodeName: "supplychain",
  // No default. Only the oracle and the regulator keep off-chain data, so for the other four
  // companies the absence of a connection string is the correct configuration rather than a
  // mistake, and the routes that need storage answer 503.
  databaseUrl: process.env.DATABASE_URL?.trim() || undefined,
  // Remembers how far the event listener has read, so a restart resumes instead of replaying the
  // whole chain. Deleting it is safe: applying an event again writes the same values.
  eventCheckpointPath: process.env.EVENT_CHECKPOINT_PATH ?? ".fabric-events.checkpoint",
  // Wallet material generated by the network, which lives in this repository. Each backend reads
  // its own company's certificate and key from here.
  fabricOrganizationsPath:
    process.env.FABRIC_ORGANIZATIONS_PATH ??
    join(repositoryRoot, "fabric", "milk-network", "organizations", "peerOrganizations")
};
