import { homedir } from "node:os";
import { join } from "node:path";

export const config = {
  port: Number(process.env.PORT ?? 3000),
  fabricChannelName: process.env.FABRIC_CHANNEL_NAME ?? "milkchannel",
  stakeholderChaincodeName: process.env.STAKEHOLDER_CHAINCODE_NAME ?? "stakeholder",
  supplychainChaincodeName: process.env.SUPPLYCHAIN_CHAINCODE_NAME ?? "supplychain",
  databaseUrl: process.env.DATABASE_URL ?? "postgres://freshmilk:freshmilk@localhost:5432/freshmilk",
  // Wallet material generated by the Fabric network. The backend reads certificates and keys
  // from here to sign as each demo stakeholder.
  fabricOrganizationsPath:
    process.env.FABRIC_ORGANIZATIONS_PATH ??
    join(homedir(), "fabric-samples", "test-network", "organizations", "peerOrganizations")
};
